title: RSE International Survey 2022
remote_theme: pmarsceill/just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  International Research Software Engineering survey (2022)
baseurl: "/international-survey-2022" # the subpath of your site, e.g.  /blog
url: "https://softwaresaved.github.io"

search_enabled: true
color_scheme: survey
exclude: ["*.py", "vendor", "survey", "docs", "cache", "data", "venv", "lib", "templates"]

collections:
  section:
    permalink: "/:collection/:path/"
    output: true
  country:
    permalink: "/:collection/:path/"
    output: true

kramdown:
  toc_levels: 2..2

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2022 Software Sustainability Institute, <a href=\"https://github.com/softwaresaved/international-survey-2018/blob/main/LICENSE\">BSD 3-Clause License</a>"

aux_links:
  "Source on GitHub":
    - "//github.com/softwaresaved/international-survey-2022"

just_the_docs:
  collections:
    section:
      name: Section
      nav_exclude: false
      search_exclude: false
    country:
      name: Country
      nav_exclude: false
      search_exclude: false
